# Generated by Django 3.2.10 on 2024-09-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_tag_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajechat',
            options={},
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='leido',
        ),
    ]
