# Generated by Django 3.2.10 on 2024-09-21 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20240921_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajechat',
            name='receptor',
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='room_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
