# Generated by Django 3.2.10 on 2024-09-21 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20240921_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajechat',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensajechat',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
