# Generated by Django 3.2.10 on 2024-09-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_perfilusuario_seguidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
    ]
