# Generated by Django 3.2.10 on 2024-09-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('umbral_puntos', models.IntegerField()),
            ],
        ),
    ]
