# Generated by Django 3.2.10 on 2024-09-24 02:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.comunidad'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
