# Generated by Django 3.2.10 on 2024-09-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_clasificacion'),
        ('social', '0013_auto_20240923_2249'),
    ]

    operations = [
    ]
