# Generated by Django 3.2.10 on 2024-09-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_action_useraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
