# Generated by Django 3.2.10 on 2024-09-25 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0016_alter_action_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('metalico', 'Premio metálico'), ('experiencia', 'Experiencia'), ('producto', 'Producto'), ('merchandising', 'Merchandising'), ('reconocimiento', 'Reconocimiento'), ('surpresa', 'Surpresa')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoConcurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resultado', models.DateField()),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.concurso')),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='concurso',
            name='premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.premio'),
        ),
    ]
