# Generated by Django 3.2.10 on 2024-09-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_adjuntorespuesta_campaign_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
