# Generated by Django 3.2.10 on 2024-09-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_respuesta_puntos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='puntos',
            new_name='puntuacion',
        ),
    ]
