# Generated by Django 5.1.1 on 2024-09-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_comunidad_publica'),
        ('social', '0020_rename_puntos_respuesta_puntuacion'),
    ]

    operations = [
    ]
