# Generated by Django 5.1.1 on 2024-09-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_merge_20240925_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
