# Generated by Django 4.2.16 on 2024-09-27 18:40

import arrow.api
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0022_alter_premio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='max_donaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='min_donaciones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='proyecto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='tipo_desafio',
            field=models.CharField(choices=[('donacion', 'Donación'), ('votacion', 'Votación')], default='donacion', max_length=10),
        ),
        migrations.AddField(
            model_name='desafio',
            name='votos_negativos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='desafio',
            name='votos_positivos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='fecha_inicio',
            field=models.DateTimeField(default=arrow.api.now),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_positivo', models.BooleanField(default=False)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='social.desafio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='social.desafio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
