# Generated by Django 4.2.16 on 2024-09-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_alter_premio_tipo'),
        ('social', '0023_like_comentario'),
    ]

    operations = [
    ]
