# Generated by Django 4.2.16 on 2024-09-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0027_alter_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/imagenes/'),
        ),
    ]
