# Generated by Django 4.2.16 on 2024-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_publicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/publicaciones/imagenes/'),
        ),
    ]
