# Generated by Django 4.2.16 on 2024-09-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_desafio_max_donaciones_desafio_min_donaciones_and_more'),
        ('social', '0029_alter_publicacion_imagen'),
    ]

    operations = [
    ]
