# Generated by Django 4.2.16 on 2024-09-27 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_merge_20240927_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='max_donaciones',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='min_donaciones',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='votos_negativos',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='votos_positivos',
        ),
        migrations.AddField(
            model_name='desafio',
            name='max_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='min_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='objetivo_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
