# Generated by Django 4.2.16 on 2024-09-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_merge_20240927_1956'),
        ('social', '0032_remove_voto_es_positivo_voto_puntuacion_and_more'),
    ]

    operations = [
    ]
