# Generated by Django 4.2.16 on 2024-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_merge_20240928_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='max_monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='min_monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='objetivo_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='tipo_desafio',
            field=models.CharField(choices=[('votacion', 'Votación'), ('donacion', 'Donación')], default='donacion', max_length=10),
        ),
    ]
