# Generated by Django 4.2.16 on 2024-09-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0035_donacioncomunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='donaciones',
            field=models.BooleanField(default=False),
        ),
    ]
