# Generated by Django 4.2.16 on 2024-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0036_comunidad_donaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/banners/'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/perfiles/'),
        ),
    ]
