# Generated by Django 4.2.16 on 2024-09-29 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0036_comunidad_donaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeChatComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='social.comunidad')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_comunidad_enviados', to=settings.AUTH_USER_MODEL)),
                ('leido_por', models.ManyToManyField(blank=True, related_name='mensajes_comunidad_leidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
