# Generated by Django 4.2.16 on 2024-09-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0037_comunidad_banner_comunidad_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='comunidades/qr_codes/')),
                ('numero_cuenta', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
