# Generated by Django 4.2.16 on 2024-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0038_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='cantidad_donada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
