# Generated by Django 4.2.16 on 2024-09-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0037_mensajechatcomunidad'),
        ('social', '0038_cuenta'),
    ]

    operations = [
    ]
