# Generated by Django 4.2.16 on 2024-09-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0039_desafio_cantidad_donada'),
        ('social', '0039_merge_0037_mensajechatcomunidad_0038_cuenta'),
    ]

    operations = [
    ]
