# Generated by Django 4.2.16 on 2024-09-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0040_alter_comunidad_banner_alter_comunidad_foto_perfil'),
        ('social', '0040_merge_20240929_1432'),
    ]

    operations = [
    ]
