# Generated by Django 4.2.16 on 2024-09-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0040_alter_comunidad_banner_alter_comunidad_foto_perfil'),
        ('social', '0041_solicitudmembresia'),
    ]

    operations = [
    ]
