# Generated by Django 4.2.16 on 2024-09-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0042_merge_20240929_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
    ]
