# Generated by Django 4.2.16 on 2024-10-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0042_alter_publicacion_imagen'),
        ('social', '0044_puntajedesafio'),
    ]

    operations = [
    ]
