# Generated by Django 4.2.16 on 2024-10-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0045_merge_20241001_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='archivos',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='videos',
        ),
        migrations.AlterField(
            model_name='archivoproyecto',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento')], max_length=10),
        ),
    ]
