# Generated by Django 4.2.16 on 2024-10-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0047_comentarioproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='comunidades/documentos_proyecto/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/imagenes_proyecto/'),
        ),
    ]
