# Generated by Django 4.2.16 on 2024-10-08 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0049_desafio_premio'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_desafios', to=settings.AUTH_USER_MODEL),
        ),
    ]
