# Generated by Django 4.2.16 on 2024-10-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0050_desafio_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='publicacion',
        ),
    ]
