# Generated by Django 4.2.16 on 2024-10-12 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0050_desafio_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
