# Generated by Django 4.2.16 on 2024-10-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0051_remove_like_publicacion'),
        ('social', '0053_firstvisit'),
    ]

    operations = [
    ]
