# Generated by Django 4.2.16 on 2024-10-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0054_merge_0051_remove_like_publicacion_0053_firstvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
