# Generated by Django 4.2.16 on 2024-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0055_useraction_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='accion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
