# Generated by Django 4.2.16 on 2024-10-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0056_useraction_accion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActividadUsuario',
        ),
    ]
