# Generated by Django 4.2.16 on 2024-10-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0057_delete_actividadusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='donaciones',
        ),
    ]
