# Generated by Django 4.2.16 on 2024-10-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0058_remove_comunidad_donaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='tags',
            field=models.ManyToManyField(to='social.tag'),
        ),
    ]
