# Generated by Django 4.2.16 on 2024-10-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0059_comunidad_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='donaciones',
            field=models.BooleanField(default=False),
        ),
    ]
