# Generated by Django 4.2.16 on 2024-10-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0060_comunidad_donaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='donaciones',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='puntaje',
        ),
    ]
