# Generated by Django 4.2.16 on 2024-10-27 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0061_remove_comunidad_donaciones_remove_desafio_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
