# Generated by Django 4.2.16 on 2024-11-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0065_alter_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='/fotos_perfil/default-avatar.svg', null=True, upload_to='fotos_perfil'),
        ),
    ]
