# Generated by Django 4.2.16 on 2024-11-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0066_alter_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidad',
            name='tags',
        ),
    ]
