# Generated by Django 4.2.16 on 2024-11-03 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0069_remove_comunidad_crowuser_solicitudcrowuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='miembros',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
