# Generated by Django 4.2.16 on 2024-11-03 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0070_alter_comunidad_miembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='crowuser',
            field=models.ManyToManyField(related_name='crowusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='miembros',
            field=models.ManyToManyField(related_name='comunidades', to=settings.AUTH_USER_MODEL),
        ),
    ]
