# Generated by Django 4.2.16 on 2024-11-03 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0071_alter_comunidad_crowuser_alter_comunidad_miembros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunidad',
            old_name='crowuser',
            new_name='crowusers',
        ),
        migrations.CreateModel(
            name='Crowuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.comunidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
