# Generated by Django 4.2.16 on 2024-11-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0072_rename_crowuser_comunidad_crowusers_crowuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcrowuser',
            name='comunidad',
        ),
        migrations.AddField(
            model_name='solicitudcrowuser',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='social.tag'),
        ),
    ]
