# Generated by Django 4.2.16 on 2024-11-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0075_remove_donacioncomunidad_nombre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Accion',
        ),
    ]
