# Generated by Django 4.2.16 on 2024-11-23 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0075_remove_donacioncomunidad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacioncomunidad',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.desafio'),
        ),
    ]
