# Generated by Django 4.2.16 on 2024-11-23 22:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0076_rename_action_accion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAction',
            new_name='AccionUsuario',
        ),
    ]
