# Generated by Django 4.2.16 on 2024-11-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0077_rename_useraction_accionusuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaign',
            new_name='Campaña',
        ),
    ]
