# Generated by Django 4.2.16 on 2024-11-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0078_rename_campaign_campaña'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tematica',
        ),
    ]
