# Generated by Django 4.2.16 on 2024-11-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0079_rename_tag_tematica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accionusuario',
            name='accion',
        ),
    ]
