# Generated by Django 4.2.16 on 2024-11-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0080_remove_accionusuario_accion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accionusuario',
            old_name='action',
            new_name='accion',
        ),
    ]
