# Generated by Django 4.2.16 on 2024-11-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0081_rename_action_accionusuario_accion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accion',
            old_name='name',
            new_name='nombre',
        ),
    ]
