# Generated by Django 4.2.16 on 2024-11-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0076_donacioncomunidad_campaign'),
        ('social', '0083_rename_points_accion_puntos'),
    ]

    operations = [
    ]
