# Generated by Django 4.2.16 on 2024-11-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0083_rename_points_accion_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
