# Generated by Django 4.2.16 on 2024-11-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0085_proyecto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
