# Generated by Django 4.2.16 on 2024-11-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0084_merge_20241123_1933'),
        ('social', '0087_campaña_slug'),
    ]

    operations = [
    ]
