# Generated by Django 4.2.16 on 2024-11-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0088_merge_0084_merge_20241123_1933_0087_campaña_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
