# Generated by Django 4.2.16 on 2024-11-24 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0089_perfilusuario_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='documentos',
            field=models.FileField(blank=True, default='', upload_to='comunidades/documentos_proyecto/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagenes',
            field=models.ImageField(blank=True, default='', upload_to='comunidades/imagenes_proyecto/'),
        ),
    ]
