# Generated by Django 4.2.16 on 2024-11-24 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0090_concurso_user_alter_proyecto_documentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='user',
            field=models.OneToOneField(default='Nadie', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
