# Generated by Django 4.2.16 on 2024-11-24 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0091_alter_concurso_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurso',
            name='user',
        ),
        migrations.AddField(
            model_name='concurso',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
