# Generated by Django 4.2.16 on 2024-11-24 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0093_alter_concurso_ganador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concurso',
            name='ganador',
        ),
    ]
