# Generated by Django 4.2.16 on 2024-11-24 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0094_remove_concurso_ganador'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganador', to=settings.AUTH_USER_MODEL),
        ),
    ]
