# Generated by Django 4.2.16 on 2024-11-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0095_concurso_ganador'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='tags',
            field=models.ManyToManyField(to='social.tematica'),
        ),
    ]
