# Generated by Django 4.2.16 on 2024-11-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0098_remove_comunidad_crowusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='tematica',
            field=models.ManyToManyField(related_name='Tema', to='social.tematica'),
        ),
    ]
