# Generated by Django 4.2.16 on 2024-11-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0100_alter_publicacion_comunidad'),
        ('social', '0100_remove_publicacion_tags_alter_publicacion_comunidad'),
    ]

    operations = [
    ]
