# Generated by Django 4.2.16 on 2024-11-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0101_merge_20241127_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
