# Generated by Django 4.2.16 on 2024-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0102_alter_perfilusuario_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='no_me_gusta',
            field=models.ManyToManyField(to='social.tematica'),
        ),
    ]
