# Generated by Django 4.2.16 on 2024-12-01 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0103_perfilusuario_no_me_gusta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tematica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.tematica'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tematica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.tematica'),
        ),
    ]
