# Generated by Django 4.2.16 on 2024-12-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0104_proyecto_tematica_publicacion_tematica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='no_me_gusta',
            field=models.ManyToManyField(null=True, to='social.tematica'),
        ),
    ]
