# Generated by Django 4.2.16 on 2024-12-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0105_alter_perfilusuario_no_me_gusta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accion',
            options={'verbose_name': 'Accion', 'verbose_name_plural': 'Acciones'},
        ),
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name': 'Clasificacion', 'verbose_name_plural': 'Clasificaciones'},
        ),
        migrations.AlterModelOptions(
            name='comunidad',
            options={'verbose_name': 'Comunidad', 'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='donacioncomunidad',
            options={'verbose_name': 'Donaciones Comunidad', 'verbose_name_plural': 'Donaciones Comunidad'},
        ),
        migrations.AlterModelOptions(
            name='mensajechat',
            options={'verbose_name': 'Mensaje Chat', 'verbose_name_plural': 'Mensajes Chat'},
        ),
        migrations.AlterModelOptions(
            name='mensajechatcomunidad',
            options={'verbose_name': 'Mensaje Chat Comunidad', 'verbose_name_plural': 'Mensajes Chat Comunidad'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='solicitudcrowuser',
            options={'verbose_name': 'Solicitud Crowdsourcer', 'verbose_name_plural': 'Solicitudes Crowdsourcer'},
        ),
        migrations.AlterModelOptions(
            name='terminoscondiciones',
            options={'verbose_name': 'Terminos Condiciones', 'verbose_name_plural': 'Terminos Condiciones'},
        ),
        migrations.AddField(
            model_name='concurso',
            name='documento',
            field=models.FileField(blank=True, default='', upload_to='concursos/documentos/'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='activada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='no_me_gusta',
            field=models.ManyToManyField(to='social.tematica'),
        ),
    ]
