# Generated by Django 4.2.16 on 2024-12-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0106_alter_accion_options_alter_clasificacion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concurso',
            old_name='documentos',
            new_name='documento',
        ),
    ]
