# Generated by Django 4.2.16 on 2024-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0107_alter_desafio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='acepta_donaciones',
            field=models.BooleanField(default=False),
        ),
    ]
