# Generated by Django 4.2.16 on 2024-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0108_comunidad_acepta_donaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='tematica',
            field=models.ManyToManyField(blank=True, null=True, related_name='Tema', to='social.tematica'),
        ),
    ]
