# Generated by Django 4.2.16 on 2024-12-17 04:05

from django.db import migrations
from django.contrib.auth.models import Group
def create_default_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Administrador de Comunidad')
    Group.objects.get_or_create(name='Crowdsourcer')

def create_default_entries(apps, schema_editor):
    Action = apps.get_model('social', 'Accion')

    # Lista de nombres para las acciones
    action_names = [
        'crear_comunidad',
        'crear_proyecto',
        'registrarse',
        'publicar',
        'donar',
        'seguir',
        'responder_campaign',
        'puntuar desafio',
        'comentar',
        'comentar proyecto',
        'crear_desafio'
    ]


    for name in action_names:
        Action.objects.create(nombre=name, puntos=0)

class Migration(migrations.Migration):

    dependencies = [
        ('social', '0109_alter_comunidad_tematica'),
    ]

    operations = [
    migrations.RunPython(create_default_groups),
    migrations.RunPython(create_default_entries),
    ]
